
import dao.ConnectionProvider;
import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import jakarta.mail.*;
import jakarta.mail.internet.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepak Shyam
 */
public class manageorder extends javax.swing.JFrame {
     private int appuserpk=0;
     private int s=0;
     private String tot=" ";
     private String Stock=" ";

    /**
     * Creates new form manageorder
     */
    public manageorder() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcustmobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcustemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtproductname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtproductprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtproductbrnd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtorderquantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtcste = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE ORDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 23, 331, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER LIST");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 103, 122, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "CONTACT", "EMAIL"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 353, 264));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODUCT LIST");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 103, 133, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY", "BRAND", "CATEGORY", "STATUS"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 555, 264));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CART");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 110, 69, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE", "SUBTOTAL"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 399, 264));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELECTED CUSTOMER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 436, 131, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 472, 37, -1));

        txtcustname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 494, 353, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MOBILE NO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 533, 353, -1));

        txtcustmobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtcustmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 555, 353, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 593, -1, -1));

        txtcustemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtcustemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 615, 353, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SELECTED PRODUCT");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 436, 154, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRODUCT NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 472, 321, -1));

        txtproductname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 555, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRODUCT PRICE ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 533, 237, -1));

        txtproductprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtproductprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 555, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRODUCT BRAND");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 593, 225, -1));

        txtproductbrnd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtproductbrnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductbrndActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductbrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 615, 555, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ORDER QUANTITY");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 647, 240, -1));

        txtorderquantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtorderquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 675, 547, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 713, 555, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL AMOUNT RS:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 186, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("00000");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 430, 108, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 571, 399, 60));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, 399, 60));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("SAVE ORDER DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 496, 397, 48));

        jLabel16.setText("EMAIL");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));
        jPanel1.add(txtcste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 350, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1750, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public class EmailSender 
    {
        public static void sendEmail(String recipientEmail,int total) 
        {
            final String senderEmail = "u359485@gmail.com";
            final String senderPassword = "khpb gvpr rdtr blno";
            Properties properties = new Properties();
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", "587");
            Session session = Session.getInstance(properties, new Authenticator() 
            {
                protected PasswordAuthentication getPasswordAuthentication() 
                {
                    return new PasswordAuthentication(senderEmail, senderPassword);
                }
            });
        try 
        {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(senderEmail));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
            message.setSubject("Purchase Confirmation");
            message.setText("Dear Customer,\n\nYour purchase has been confirmed!\n\nBest Regards,\nVenus Engineering works for a total of:"+total+"\n\nThankyou for choosing Venus engineering works");
            Transport.send(message);
            System.out.println("Email sent successfully!");
        } 
        catch (MessagingException e) 
        {
            e.printStackTrace();
        }
    }
}

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        DefaultTableModel m2=(DefaultTableModel) jTable2.getModel();
        DefaultTableModel m3=(DefaultTableModel) jTable3.getModel();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from customer");
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("customer_pk"),rs.getString("nme"),rs.getString("mobileno"),rs.getString("email")});
            }
            Statement s2=con.createStatement();
            ResultSet r2=s2.executeQuery("select * from products");
            while (r2.next()) {
                String ProductID = String.valueOf(r2.getInt("ProductID")); 
                String Name = r2.getString("Name"); 
                String Category = r2.getString("Category");
                String Price = String.valueOf(r2.getDouble("Price"));
                Stock = String.valueOf(r2.getInt("Stock"));  
                String Status = r2.getString("Status");
                String brand = r2.getString("Brand");
                String tbd[] = {ProductID, Name, Price, Stock,brand,Category,Status};
                m2.addRow(tbd);
            }
            Statement s3=con.createStatement();
            ResultSet r3=s3.executeQuery("select * from cart");
            m3.setRowCount(0);
            while (r3.next()) {
                String pID = String.valueOf(r3.getInt("cartpk_id")); 
                String pName = r3.getString("pName"); 
                String Price = r3.getString("price");
                String pq = r3.getString("quantity");
                String se;
                se= String.valueOf(r3.getInt("subtotal"));
                String tb2[]={pID,pName, Price, pq,se};
                m3.addRow(tb2);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void txtproductbrndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductbrndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductbrndActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home h=new Home();
        h.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String id=model.getValueAt(index,0).toString();
        appuserpk=Integer.parseInt(id);
        String name=model.getValueAt(index,1).toString();
        txtcustname.setText(name);
        String mobilenumber=model.getValueAt(index,2).toString();
        txtcustmobile.setText(mobilenumber);
        String email=model.getValueAt(index,3).toString();
        txtcustemail.setText(id);
        txtcste.setText(email);
    }//GEN-LAST:event_jTable1MouseClicked
    String pnm;
    String pp;
    String pd;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int ind=jTable2.getSelectedRow();
        TableModel mo2=jTable2.getModel();
        pnm=mo2.getValueAt(ind,1).toString();
        txtproductname.setText(pnm);
        pp=mo2.getValueAt(ind,2).toString();
        txtproductprice.setText(pp);
        pd=mo2.getValueAt(ind,4).toString();
        txtproductbrnd.setText(pd);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String quantityStr = txtorderquantity.getText();
    String productName = txtproductname.getText();
    String priceStr = txtproductprice.getText();
    String pid = txtcustemail.getText();  // Assuming pid is used somewhere else

    if (quantityStr.isEmpty() || productName.isEmpty() || priceStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        return;
    }

    int quantity;
    double price;

try {
    quantity = Integer.parseInt(quantityStr);
    price = Double.parseDouble(priceStr);
    if (quantity <= 0 || price < 0) {
        JOptionPane.showMessageDialog(null, "Quantity must be greater than 0 and price must be non-negative.");
        return;
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Please enter valid numbers for quantity and price.");
    return;
}

double subtotal = quantity * price;
s += subtotal;
tot = String.valueOf(s);

try (Connection con = ConnectionProvider.getCon()) {

    // Step 1: Check current stock
    int currentStock = 0;
    try (PreparedStatement ptStock = con.prepareStatement("SELECT Stock FROM products WHERE Name = ?")) {
        ptStock.setString(1, productName);
        ResultSet rs = ptStock.executeQuery();
        if (rs.next()) {
            currentStock = rs.getInt("Stock");
        } else {
            JOptionPane.showMessageDialog(null, "Product not found in inventory.");
            return;
        }
    }
    if (currentStock < quantity) {
        JOptionPane.showMessageDialog(null, "Not enough stock available.");
        return;
    }
    try (PreparedStatement pt2 = con.prepareStatement("INSERT INTO cart(pname, price, quantity, subtotal) VALUES (?, ?, ?, ?)")) {
        pt2.setString(1, productName);
        pt2.setDouble(2, price);
        pt2.setInt(3, quantity);
        pt2.setDouble(4, subtotal);
        int rowsAffected = pt2.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Insertion successful");
            setVisible(false);
            jLabel15.setText(tot);
            setVisible(true);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            refreshProductTable();
            refreshCustomerTable();

        } else {
            JOptionPane.showMessageDialog(null, "Insertion failed. No rows affected.");
        }
    }
    int newStock = currentStock - quantity;
    try (PreparedStatement pt3 = con.prepareStatement("UPDATE products SET Stock = ? WHERE Name = ?")) {
        pt3.setInt(1, newStock);
        pt3.setString(2, productName);
        pt3.executeUpdate();
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
}
 
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshCartTable() {
    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    model.setRowCount(0); 
    try (Connection con = ConnectionProvider.getCon();
         PreparedStatement ps = con.prepareStatement("SELECT * FROM cart");
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] row = {
                rs.getString("pname"),
                rs.getBigDecimal("price"),
                rs.getInt("quantity"),
                rs.getBigDecimal("subtotal")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading cart data: " + e.getMessage());
    }
}
    private void refreshProductTable() throws SQLException {
    DefaultTableModel m2= (DefaultTableModel) jTable2.getModel();
    m2.setRowCount(0); 
    try (Connection con = ConnectionProvider.getCon();
         PreparedStatement ps = con.prepareStatement("SELECT * FROM products");
         ResultSet r2 = ps.executeQuery()) {
            while (r2.next()) {
                String ProductID = String.valueOf(r2.getInt("ProductID")); 
                String Name = r2.getString("Name"); 
                String Category = r2.getString("Category");
                String Price = String.valueOf(r2.getDouble("Price"));
                Stock = String.valueOf(r2.getInt("Stock"));  
                String Status = r2.getString("Status");
                String brand = r2.getString("Brand");
                String tbd[] = {ProductID, Name, Price, Stock,brand,Category,Status};
                m2.addRow(tbd);
            }
        }
    catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading product data: " + e.getMessage());
    }
    }
    private void refreshCustomerTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing rows

    try {
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from customer");
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("customer_pk"),rs.getString("nme"),rs.getString("mobileno"),rs.getString("email")});
            }
        }
    catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading customer data: " + e.getMessage());
    }
    }


    private void txtproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
      try {
    Connection con = ConnectionProvider.getCon();
    PreparedStatement selectCart = con.prepareStatement("SELECT pname, quantity FROM cart");
    ResultSet rs = selectCart.executeQuery();
    while (rs.next()) {
        String pname = rs.getString("pname");
        int cartQty = rs.getInt("quantity");
        PreparedStatement getStock = con.prepareStatement("SELECT Stock FROM products WHERE Name = ?");
        getStock.setString(1, pname);
        ResultSet stockRs = getStock.executeQuery();

        if (stockRs.next()) {
            int currentStock = stockRs.getInt("Stock");
            int updatedStock = currentStock + cartQty;
            PreparedStatement updateStock = con.prepareStatement("UPDATE products SET Stock = ? WHERE Name = ?");
            updateStock.setInt(1, updatedStock);
            updateStock.setString(2, pname);
            updateStock.executeUpdate();
        }
    }
    PreparedStatement pt3 = con.prepareStatement("DELETE FROM cart");
    pt3.executeUpdate();
    JOptionPane.showMessageDialog(null, "Cart cleared and stock restored successfully!");
    manageorder m = new manageorder();
    m.setVisible(false);
    m.setVisible(true);
    tot = "00000";
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String email = txtcustemail.getText();
    String name = txtcustname.getText();
    String total = jLabel15.getText();
    String px=txtcste.getText();

if (email.isEmpty() || name.isEmpty() || total.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Missing customer details!");
    return;
}

try (Connection con = ConnectionProvider.getCon();
     PreparedStatement pst = con.prepareStatement("INSERT INTO orderhistory (email, name, total, order_date) VALUES (?, ?, ?, NOW())")) {

    pst.setString(1, email);
    pst.setString(2, name);
    pst.setString(3, total);

    int rows = pst.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(null, "Order history saved!");
        generatePDFInvoice(email, name, total);
        PreparedStatement clearCart = con.prepareStatement("DELETE FROM cart");
        clearCart.executeUpdate();
        JOptionPane.showMessageDialog(null, "Cart cleared successfully!");
        jLabel15.setText("00000");
        manageorder m = new manageorder();
        m.setVisible(false);
        m.setVisible(true);

    } else {
        JOptionPane.showMessageDialog(null, "Failed to save order history.");
    }
    EmailSender.sendEmail(px,Integer.parseInt(total));

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}


    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtproductpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductpriceActionPerformed

private void generatePDFInvoice(String email, String name, String total) {
    try {
        String fileName = "Bill_" + name + "_" + System.currentTimeMillis() + ".pdf";
        Document document = new Document(PageSize.A4, 30, 30, 30, 30);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();
        PdfContentByte canvas = writer.getDirectContent();
        Rectangle border = new Rectangle(document.getPageSize());
        border.setLeft(20);
        border.setRight(document.getPageSize().getWidth() - 20);
        border.setTop(document.getPageSize().getHeight() - 20);
        border.setBottom(20);
        border.setBorder(Rectangle.BOX);
        border.setBorderWidth(1);
        canvas.rectangle(border);
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
        Paragraph title = new Paragraph("Invoice", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        Font small = new Font(Font.FontFamily.HELVETICA, 10);
        Paragraph date = new Paragraph("Date: " + new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date()), small);
        date.setAlignment(Element.ALIGN_RIGHT);
        document.add(date);
        Font regular = new Font(Font.FontFamily.HELVETICA, 12);
        document.add(new Paragraph("Customer Name: " + name, regular));
        document.add(new Paragraph("Customer Email: " + email, regular));
        document.add(new Paragraph(" "));
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        table.setSpacingAfter(10f);
        table.addCell("Product Name");
        table.addCell("Price");
        table.addCell("Quantity");
        table.addCell("Subtotal");
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM cart");
        while (rs.next()) {
            table.addCell(rs.getString("pname"));
            table.addCell("₹" + rs.getString("price"));
            table.addCell(rs.getString("quantity"));
            table.addCell("₹" + rs.getString("subtotal"));
        }
        document.add(table);
        Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        Paragraph totalPara = new Paragraph("Total Amount: ₹" + total, totalFont);
        totalPara.setAlignment(Element.ALIGN_RIGHT);
        document.add(totalPara);
        Paragraph footer = new Paragraph("Thank you for choosing Venus Engineering Works!", small);
        footer.setAlignment(Element.ALIGN_BASELINE);
        footer.setSpacingBefore(20);
        document.add(footer);

        document.close();
        JOptionPane.showMessageDialog(null, "PDF Invoice generated: " + fileName);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "PDF generation error: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageorder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtcste;
    private javax.swing.JTextField txtcustemail;
    private javax.swing.JTextField txtcustmobile;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtorderquantity;
    private javax.swing.JTextField txtproductbrnd;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductprice;
    // End of variables declaration//GEN-END:variables
}
